In [2]:
import numpy as np

In [3]:
a = np.array([[7,4],
              [5,3]])
a

array([[7, 4],
       [5, 3]])

In [4]:
b = np.array([655,475])
b

array([655, 475])

In [5]:
from numpy.linalg import inv

In [6]:
a_inverse =inv(a)
inv(a)

array([[ 3., -4.],
       [-5.,  7.]])

In [7]:
np.dot(a_inverse,b)

array([65., 50.])

In [ ]:
# for linear algebra question degree need to one

In [1]:
# A.x = B ,
# x = A(inv).B

# A(inv) = 1/A (Flase)
# A(inv) = 1/|A|. adj(A) (True)
# |A| = Determinent of A
# adj(a) = Adjoint of A

In [2]:
# Determinent of 2-D matrix

# 1 1  = (1*7)-(1*4)    =>  7-4  => 3
# 4 7

# Determinent of 3-D matrix

# 2 5 8
# 1 4 3 = +2(4*4 - 3*2)  -5(4*1 - 8*3)  +8(2*1 - 8*4)  =>  2(16-6) -5(4-24)  +8(2-32)  => 2(10) -5(-20) +8(-30)
# 8 2 4             => 20 + 100 - 240   => -120

#Determinent is calculated on sqr matrix

# Determinent of Matrix

In [3]:
import numpy as np
from numpy.linalg import det

In [5]:
A = np.array([[2,3,1],
              [1,2,3],
              [4,2,6]])
A

array([[2, 3, 1],
       [1, 2, 3],
       [4, 2, 6]])

In [8]:
det(A) #this will find the Determinent of matrix A

23.999999999999993

# Inverse of the Matrix

In [9]:
from numpy.linalg import inv

In [10]:
inv(A)

array([[ 0.25      , -0.66666667,  0.29166667],
       [ 0.25      ,  0.33333333, -0.20833333],
       [-0.25      ,  0.33333333,  0.04166667]])

In [13]:
C = np.array([[2,3],
              [1,2]])
C

array([[2, 3],
       [1, 2]])

In [16]:
C_inv= inv(C) #this inc function conpute the inverse matrix
C_inv

array([[ 2., -3.],
       [-1.,  2.]])

In [ ]:
# element wise matrix addition

#    2 4  +  3 6   =   5 10
#    6 1     1 2       7 3

In [17]:
# element wise Matrix Subtraction

#    2 4  -  3 6   =   -1 -2
#    6 1     1 2        5 -1

In [10]:
F = np.array([[8,3],
              [4,2]])
G = np.array([[7,3],
              [5,1]])

In [11]:
F+G

array([[15,  6],
       [ 9,  3]])

In [12]:
F-G

array([[ 1,  0],
       [-1,  1]])

# Matrix Multiplication (element wise)

In [14]:
A = np.array([[1,3],
              [2,2]])
B = np.array([[2,1],
              [5,1]])
A*B

array([[ 2,  3],
       [10,  2]])

# Matrix Multiplication (Dot Product)

In [15]:
np.dot(A,B)

array([[17,  4],
       [14,  4]])

In [16]:
# Matrix A      Matrix B
# 2  1           3  2
# 3  2           2  4

# element wise    6  2
#                 6  8
    
# Dot product  2*3 + 1*2            2*2 + 1*4           =>    6+2   4+4           =>  8  8
#              3*3 + 2*2            3*3 + 2*4                 9+4   9+8               13 17

# Solution to system of linear equation

1. find the inverse a
2. product of inverse_a * b

In [29]:
A = np.array([[5,3],
              [7,4]])
B = np.array([475,655])

In [30]:
A

array([[5, 3],
       [7, 4]])

In [31]:
B

array([475, 655])

In [32]:
A_inv = inv(A)
A_inv

array([[-4.,  3.],
       [ 7., -5.]])

In [33]:
np.dot(A_inv,B)

array([65., 50.])

In [35]:
np.dot(B,A_inv) #This is the wrong solu bcz we switch the oprands

array([ 2685., -1850.])